### ISSUE TITLE
esp-backtrace failed to compile on nightly 1.81

### ISSUE THREAD

**Issue by danclive** [esp-rs/esp-hal#1682]
The recent nightly 1.81 changed the [core::panic::PanicInfo](https://doc.rust-lang.org/nightly/core/panic/struct.PanicInfo.html) structure.

Error Message:

```sh
error[E0308]: mismatched types
  --> /home/danc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-backtrace-0.12.0/src/lib.rs:79:16
   |
79 |         if let Some(message) = info.message() {
   |                ^^^^^^^^^^^^^   -------------- this expression has type `Arguments<'_>`
   |                |
   |                expected `Arguments<'_>`, found `Option<_>`
   |
   = note: expected struct `Arguments<'_>`
                found enum `Option<_>`
help: you might have meant to use field `fmt` whose type is `Option<&[core::fmt::rt::Placeholder]>`
   |
79 |         if let Some(message) = info.message().fmt {
   |                                ~~~~~~~~~~~~~~~~~~

```
