### PR TITLE
Fix esp-storage dep version

### LINKED ISSUE #6241: esp-bootloader-esp-idf 0.6 doesn't work with the new esp-hal 1.2 beta.
## Bug description
Using the new esp-hal 1.2 beta version and updated 0.6 version of esp-bootloader-esp-flash, I get this error:  (but compiles fine if you cargo clean after changing to the previous 0.5 version)

error[E0425]: cannot find function `esp_rom_spiflash_write_encrypted` in this scope
  --> /home/woody/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-storage-0.10.0/src/hardware.rs:35:27
   |
35 |         let rc = unsafe { esp_rom_spiflash_write_encrypted(dest_addr, data, len) };
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `esp-storage` (lib) due to 1 previous error

## To Reproduce

This is almost verbatim code that esp-generate makes for esp32c6.  I added enough to generate the bug.

[BUG:esp-bootloader-esp-idf.zip](https://github.com/user-attachments/files/31604777/BUG.esp-bootloader-esp-idf.zip)

1. endure esp-bootloader-esp-idf is set to 0.5 in Cargo.toml
2. cargo clean
3. cargo build
4. (success!)
5. change to 0.6 in Cargo.toml
6. cargo clean
7. cargo build
8. <above error>

## Expected behavior

No compile errors

## Environment

- Target device: [e.g. ESP32-c6] 
- Crate name and version: [e.g. esp-hal 1.2.0-rc.0]

### PR DESCRIPTION
**Pull request by bugadani**
esp-storage is using a feature that was introduced in esp-rom-sys 0.1.5, so it can't just depend on any `0.1.x` version.

Closes #6241

### CODE REVIEW

**Comment by bjoernQ** [comment]
might be worth to update https://github.com/esp-rs/esp-hal/tree/main/esp-rom-sys#dependency-policy-in-the-esp-hal-workspace

**Comment by MabezDev** [comment]
Won't this cause dependency issues, shouldn't we pin all to the specific version?

**Comment by bugadani** [comment]
I don't know, but right now we let cargo pull in an older version, and that's _definitely_ incorrect. We can't predict which future version will introduce a breaking change, so we can't put an upper bound. We can pin `0.1.5` but that will conflict with a future esp-radio update that pins e.g. `0.1.6`. There are no good solutions here with what esp-rom-sys tried to do right now.

**Comment by bjoernQ** [comment]
this should fix it - but I'm wondering if the real issue isn't https://github.com/esp-rs/esp-hal/issues/6241#issuecomment-5475239713

(i.e. the reason 0.1.5 wasn't pulled in)

but even with bumping the rust version it needs a `cargo update`

**Comment by bugadani** [comment]
We are using a function that we added in 0.1.5, so we should declare that we need at least 0.1.5 of the dependency, as simple as that. There is a switch in cargo that forces a project to use the minimum version of the declared dependencies, and that would fail regardless of the rust version that esp-generate gives. esp-hal's msrv is already 1.95

**Comment by bjoernQ** [comment]
Yes - but still we should update the esp-rom-sys README IMHO

**Comment by bugadani** [comment]
Which part? This change is covered by `Most crates use a non-exact requirement on the 0.1.x line (for example ~0.1 / ~0.1.x), so they can consume compatible patch updates.`, just not with one of the given examples.

For `0.x` crates, `~0.1.x` and `0.1.x` (or `~0.1` and `0.1`) are equivalent.

**Comment by bjoernQ** [comment]
`Crates that are tightly coupled to a specific radio/blob behavior pin an exact esp-rom-sys patch version (e.g. esp-radio).`

**Comment by bugadani** [comment]
And what radio/blob behaviour do we use by calling the `esp_rom_spiflash_write_encrypted` function?

**Comment by bjoernQ** [comment]
ok - that was the wrong sentence .... 🙈 

this should work for: `version = "0.1.5"` will allow esp-radio rc.1 to require `version = "=0.1.6" and we end up with 0.1.6? 

but will break the `=0.1.4` in esp-radio 1.0.0-beta.0

> There are no good solutions here with what esp-rom-sys tried to do right now.

Unfortunately yes - and sure - we don't need to update the esp-rom-sys README here and now (if at all)

**Comment by bugadani** [comment]
> but will break the =0.1.4 in esp-radio 1.0.0-beta.0

Since https://github.com/esp-rs/esp-hal/pull/5810 wasn't a part of esp-rom-sys 0.1.4, esp-storage 0.10 is simply not compatible with esp-radio 1.0.0-beta.0 because of that pinned version. Yes, it will break, because our policy is for it to break, because we pin the rom-sys version for radio.

Maybe we need to revisit this version policy, e.g. we maybe can bump the minor version component when we update radio blobs, but either approach has downsides.

**Comment by bjoernQ** [comment]
so I guess this is good to merge and release? esp-radio 1.0.0-beta.0 isn't supposed to work with 1.2.0 anyways?

**Comment by MabezDev** [comment]
Okay, I think I understand this now. A bare `0.1.5` doesn't pin, it's the same as `^0.1.5`, which is `>=0.1.5, <0.2.0`. This is okay, as we cargo will always resolve a higher one if there is a higher one that satisfies all constraints, so we can use these constraints in the future to ensure a rom-sys has X API. The pinning rule still stands for esp-radio, it's on the only crate allowed to pin (though maybe we need to revisit that as msrv aware resolving might mess this up.)

**Review by MabezDev — APPROVED** [review]
