### ISSUE TITLE
esp-bootloader-esp-idf 0.6 doesn't work with the new esp-hal 1.2 beta.

### ISSUE THREAD

**Issue by Hackswell** [esp-rs/esp-hal#6241]
## Bug description
Using the new esp-hal 1.2 beta version and updated 0.6 version of esp-bootloader-esp-flash, I get this error:  (but compiles fine if you cargo clean after changing to the previous 0.5 version)

error[E0425]: cannot find function `esp_rom_spiflash_write_encrypted` in this scope
  --> /home/woody/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/esp-storage-0.10.0/src/hardware.rs:35:27
   |
35 |         let rc = unsafe { esp_rom_spiflash_write_encrypted(dest_addr, data, len) };
   |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0425`.
error: could not compile `esp-storage` (lib) due to 1 previous error

## To Reproduce

This is almost verbatim code that esp-generate makes for esp32c6.  I added enough to generate the bug.

[BUG:esp-bootloader-esp-idf.zip](https://github.com/user-attachments/files/31604777/BUG.esp-bootloader-esp-idf.zip)

1. endure esp-bootloader-esp-idf is set to 0.5 in Cargo.toml
2. cargo clean
3. cargo build
4. (success!)
5. change to 0.6 in Cargo.toml
6. cargo clean
7. cargo build
8. <above error>

## Expected behavior

No compile errors

## Environment

- Target device: [e.g. ESP32-c6] 
- Crate name and version: [e.g. esp-hal 1.2.0-rc.0]

**Comment by bugadani** [comment]
For some reason, the project pulls in `esp-rom-sys v0.1.4` which doesn't export `esp_rom_spiflash_write_encrypted`. Adding `esp-rom-sys = "0.1.5"` helps, but we might want an esp-storage release that actually requires it instead of `~0.1` (which is weird anyway since cargo won't try to pull in 0.2).

**Comment by Hackswell** [comment]
I confirm that this workaround works.

**Comment by bjoernQ** [comment]
Not sure I followed all the steps exactly but maybe this

```
   Unchanged esp-rom-sys v0.1.4 (available: v0.1.5, requires Rust 1.95.0)
```

this is a hint. Released `esp-generate`  1.3.0 contains this 

https://github.com/esp-rs/esp-generate/blob/85210011fd41b07182bd8c7b6b4319b8436f3989/template/Cargo.toml#L6

```
rust-version = "1.88"
```

After updating , `cargo update` pulled in `esp-bootloader-esp-idf` 0.1.5 as expected.
